// SPDX-License-Identifier: BSD-3-Clause
// Umbrella header.
#pragma once

#include "xinn/shape.hpp"
#include "xinn/tensor.hpp"
#include "xinn/concepts.hpp"
#include "xinn/constant.hpp"
#include "xinn/parallel.hpp"
#include "xinn/expr.hpp"
#include "xinn/ops.hpp"
#include "xinn/linalg.hpp"
#include "xinn/reduce.hpp"
#include "xinn/loss.hpp"
#include "xinn/conv.hpp"
#include "xinn/param.hpp"
#include "xinn/init.hpp"
#include "xinn/autograd.hpp"
#include "xinn/module.hpp"
#include "xinn/layers.hpp"
#include "xinn/io.hpp"
#include "xinn/optim.hpp"
#include "xinn/rnn.hpp"
#include "xinn/data.hpp"
#include "xinn/metrics.hpp"
#include "xinn/datasets.hpp"
#include "xinn/describe.hpp"
#include "xinn/format.hpp"
#include "xinn/attention.hpp"
#include "xinn/shared.hpp"
#include "xinn/transformer.hpp"
#include "xinn/gnn.hpp"
